#!/usr/bin/env node
// dev-up.mjs - Start PULO local development environment with Docker

import { execSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const PROJECT_ROOT = new URL('.', import.meta.url).pathname;

function loadEnv(path) {
  try {
    const env = {};
    readFileSync(path, 'utf-8').split('\n').forEach(line => {
      const match = line.match(/^([^=]+)=(.*)$/);
      if (match) env[match[1].trim()] = match[2].trim();
    });
    return env;
  } catch {
    return {};
  }
}

const env = { ...loadEnv(join(PROJECT_ROOT, '.env')) };

async function isPortOccupied(port) {
  const { default: net } = await import('net');
  return new Promise(resolve => {
    const server = net.createServer();
    server.once('error', () => resolve(true));
    server.once('listening', () => { server.close(); resolve(false); });
    server.listen(port, '0.0.0.0');
  });
}

async function findFreePort(start) {
  for (let port = start; port < start + 100; port++) {
    if (!await isPortOccupied(port)) return port;
  }
  return null;
}

async function detectPorts() {
  const PREFERRED = {
    PULO_API_PORT: parseInt(env.PULO_API_PORT) || 4311,
    PULO_WEB_PORT: parseInt(env.PULO_WEB_PORT) || 3000,
    PULO_WORKER_PORT: parseInt(env.PULO_WORKER_PORT) || 4321,
    PULO_POSTGRES_PORT: parseInt(env.PULO_POSTGRES_PORT) || 5432,
    PULO_REDIS_PORT: parseInt(env.PULO_REDIS_PORT) || 6379,
  };

  const detected = {};
  const shifted = {};

  for (const [name, preferred] of Object.entries(PREFERRED)) {
    const occupied = await isPortOccupied(preferred);
    if (occupied) {
      const free = await findFreePort(preferred + 1);
      if (free) {
        detected[name] = free;
        shifted[name] = { was: preferred, now: free };
      } else {
        throw new Error(`Cannot find free port near ${preferred} for ${name}`);
      }
    } else {
      detected[name] = preferred;
    }
  }

  return { detected, shifted };
}

function writeGeneratedEnv(detected) {
  const lines = [
    '# Auto-generated local ports (do not commit)',
    '# Generated by scripts/dev-up.mjs',
    '',
    ...Object.entries(detected).map(([k, v]) => `${k}=${v}`),
    '',
    '# Database',
    `POSTGRES_USER=${env.POSTGRES_USER || 'pulo'}`,
    `POSTGRES_PASSWORD=${env.POSTGRES_PASSWORD || 'pulo_dev_password'}`,
    `POSTGRES_DB=${env.POSTGRES_DB || 'pulo_dev'}`,
    '',
    '# Redis',
    'REDIS_URL=redis://localhost:6379',
    '',
    '# API URL for web',
    `NEXT_PUBLIC_API_URL=http://localhost:${detected.PULO_API_PORT}`,
  ];

  writeFileSync(join(PROJECT_ROOT, '.env.local.generated'), lines.join('\n'));
  console.log('  📝 Wrote .env.local.generated');
}

function stopContainer(name) {
  try {
    execSync(`docker stop ${name}`, { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

async function main() {
  console.log('\n🚀 PULO Local Development Setup\n' + '─'.repeat(50));

  // Stop existing containers
  console.log('\n📦 Stopping existing containers...');
  const containers = ['pulo_api', 'pulo_web', 'pulo_worker', 'pulo_postgres', 'pulo_redis'];
  containers.forEach(name => {
    const stopped = stopContainer(name);
    if (stopped) console.log(`  Stopped ${name}`);
  });

  // Detect ports
  console.log('\n🔍 Detecting ports...');
  const { detected, shifted } = await detectPorts();

  if (Object.keys(shifted).length > 0) {
    console.log('\n⚠️  Port conflicts detected, using alternatives:');
    Object.entries(shifted).forEach(([name, { was, now }]) => {
      console.log(`  ${name}: ${was} → ${now}`);
    });
  }

  // Write env
  writeGeneratedEnv(detected);

  // Build images
  console.log('\n🔨 Building Docker images...');
  try {
    execSync('docker compose build', { cwd: PROJECT_ROOT, stdio: 'inherit' });
  } catch (e) {
    console.error('Build failed:', e.message);
    process.exit(1);
  }

  // Start services
  console.log('\n▶️  Starting services...');
  execSync('docker compose up -d', { cwd: PROJECT_ROOT, stdio: 'inherit' });

  // Wait and verify
  console.log('\n⏳ Waiting for services to be healthy...\n');

  const maxWait = 60;
  let waited = 0;

  const checkHealth = async () => {
    const { default: net } = await import('net');
    const checks = [
      { name: 'Postgres', port: detected.PULO_POSTGRES_PORT, path: null },
      { name: 'Redis', port: detected.PULO_REDIS_PORT, path: null },
      { name: 'API', port: detected.PULO_API_PORT, path: '/health' },
    ];

    for (const check of checks) {
      const ready = await new Promise(resolve => {
        if (check.path === null) {
          const server = net.createServer();
          server.once('error', () => resolve(false));
          server.once('listening', () => { server.close(); resolve(true); });
          server.listen(check.port, '127.0.0.1');
        } else {
          const http = await import('http');
          http.get(`http://127.0.0.1:${check.port}${check.path}`, r => resolve(r.statusCode === 200)).on('error', () => resolve(false));
        }
      });
      if (!ready) throw new Error(`${check.name} not ready`);
    }
  };

  while (waited < maxWait) {
    try {
      await checkHealth();
      console.log('  ✅ All services are healthy');
      break;
    } catch {
      await new Promise(r => setTimeout(r, 2000));
      waited += 2;
    }
  }

  if (waited >= maxWait) {
    console.log('  ⚠️  Some services may not be fully ready yet');
  }

  console.log('\n' + '═'.repeat(50));
  console.log('  🟢 PULO Local Stack Started');
  console.log('═'.repeat(50));
  console.log('\n  📍 Services:');
  console.log(`     API:     http://localhost:${detected.PULO_API_PORT}`);
  console.log(`     Web:     http://localhost:${detected.PULO_WEB_PORT}`);
  console.log(`     Worker:  http://localhost:${detected.PULO_WORKER_PORT}`);
  console.log(`     Postgres: localhost:${detected.PULO_POSTGRES_PORT}`);
  console.log(`     Redis:   localhost:${detected.PULO_REDIS_PORT}`);
  console.log('\n  📝 Config:  .env.local.generated');
  console.log('  📜 Logs:    pnpm docker:logs');
  console.log('  🛑 Stop:    pnpm docker:down');
  console.log('═'.repeat(50) + '\n');
}

main().catch(e => {
  console.error('Error:', e.message);
  process.exit(1);
});